#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

logger "Stopping Daemon(USBIPD)" -t"unraid.usbip-gui"
${DOCROOT}/plugins/usb_manager/scripts/rc.usb_manager stop_daemon

#logger "Detach All USBIP Devices..." -t"unraid.usbip-gui"
#${DOCROOT}/plugins/unraid.usbip-gui/scripts/rc.unraid.usbip-gui detach_ports
